### ISSUE TITLE
Concurrent modification when ending idle conversations.

### ISSUE THREAD

**Issue by Celos** [tynamo/tapestry-conversations#8]
ConversationManagerImpl#endIdleConversations does not synchronize over the conversations map and can cause ConcurrentModificationExceptions.

**Comment by kaosko** [comment]
Thanks, yes absolutely. Your patch is hosed though, do not reformat code meant for pull requests. If you fix that I can merge a clean request in or I can just add the sync in manually.

**Comment by kaosko** [comment]
Fixed
